/**
 * Seed AircraftManufacturer, AircraftFamily, AircraftVariant, and Airline
 * tables from curated CSV files.
 *
 * These CSVs should be placed in prisma/data/:
 *   - manufacturers.csv   — AircraftManufacturer records
 *   - families.csv        — AircraftFamily records (references manufacturers)
 *   - variants.csv         — AircraftVariant records (References families + AircraftType)
 *   - airlines.csv         — Airline records
 *
 * Format for manufacturers.csv:
 *   name,country
 *   Boeing,United States
 *   Airbus,France
 *
 * Format for families.csv:
 *   name,manufacturer_name
 *   737,Boing
 *   747-8,Boeing
 *
 * Format for variants.csv:
 *   name,family_name,aircraft_type_icao
 *   737-86N,737,B738
 *   747-8i,747-8,
 *
 * Format for airlines.csv:
 *   name,icaoCode,iataCode,country,callsign
 *   American Airlines,AAL,AA,United States,AMERICAN
 *
 * Usage:
 *   npx tsx prisma/seed-aircraft-hierarchy.ts
 *
 * The CSV files should be curated manually (or via the draft generated by
 * scripts/generate-aircraft-hierarchy-draft.ts) — this script is idempotent
 * and safe to re-run.
 */

import { readFileSync, readdirSync } from 'node:fs';
import { join } from 'node:path';

import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const DATA_DIR = join(process.cwd(), 'prisma', 'data');

interface ManufacturerRow { name: string; country?: string }
interface FamilyRow { name: string; manufacturer_name: string }
interface VariantRow { name: string; family_name: string; aircraft_type_icao?: string }
interface AirlineRow { name: string; icaoCode?: string; iataCode?: string; country?: string; callsign?: string }

function parseCSV(filepath: string): Record<string, string>[] {
  const text = readFileSync(filepath, 'utf-8');
  const lines = text.split('\n').map(l => l.trim()).filter(l => l && !l.startsWith('#'));
  if (lines.length < 2) return [];
  const headers = lines[0].split(',').map(h => h.trim().toLowerCase());
  return lines.slice(1).map(line => {
    const fields = line.split(',').map(f => f.trim().replace(/^"|"$/g, ''));
    const obj: Record<string, string> = {};
    headers.forEach((h, i) => { obj[h] = fields[i] ?? ''; });
    return obj;
  });
}

async function seedManufacturers(rows: ManufacturerRow[]) {
  let created = 0, updated = 0;
  for (const row of rows) {
    if (!row.name) continue;
    const existing = await prisma.aircraftManufacturer.findUnique({ where: { name: row.name } });
    if (existing) {
      if (existing.country !== row.country) {
        await prisma.aircraftManufacturer.update({ where: { name: row.name }, data: { country: row.country || null } });
        updated++;
      }
    } else {
      await prisma.aircraftManufacturer.create({ data: { name: row.name, country: row.country || null } });
      created++;
    }
  }
  console.log(`  ✅ Manufacturers: ${created} created, ${updated} updated`);
}

async function seedFamilies(rows: FamilyRow[]) {
  let created = 0, updated = 0, skipped = 0;
  for (const row of rows) {
    if (!row.name || !row.manufacturer_name) continue;
    const manufacturer = await prisma.aircraftManufacturer.findUnique({ where: { name: row.manufacturer_name } });
    if (!manufacturer) { console.warn(`  ⚠️  Family "${row.name}": manufacturer "${row.manufacturer_name}" not found, skipping`); skipped++; continue; }
    const existing = await prisma.aircraftFamily.findUnique({ where: { name: row.name } });
    if (existing) {
      if (existing.manufacturerId !== manufacturer.id) {
        await prisma.aircraftFamily.update({ where: { name: row.name }, data: { manufacturerId: manufacturer.id } });
        updated++;
      }
    } else {
      await prisma.aircraftFamily.create({ data: { name: row.name, manufacturerId: manufacturer.id } });
      created++;
    }
  }
  console.log(`  ✅ Families: ${created} created, ${updated} updated, ${skipped} skipped (no manufacturer)`);
}

async function seedVariants(rows: VariantRow[]) {
  let created = 0, updated = 0, skipped = 0;
  for (const row of rows) {
    if (!row.name || !row.family_name) continue;
    const family = await prisma.aircraftFamily.findUnique({ where: { name: row.family_name } });
    if (!family) { console.warn(`  ⚠️  Variant "${row.name}": family "${row.family_name}" not found, skipping`); skipped++; continue; }
    let aircraftTypeId: string | null = null;
    if (row.aircraft_type_icao) {
      // Look up by icaoCode OR iataCode (some AircraftTypes only have one)
      const at = await prisma.aircraftType.findFirst({
        where: { OR: [{ icaoCode: row.aircraft_type_icao }, { iataCode: row.aircraft_type_icao }] },
      });
      aircraftTypeId = at?.id ?? null;
    }
    const existing = await prisma.aircraftVariant.findUnique({ where: { name: row.name } });
    if (existing) {
      const needsUpdate: { familyId?: string; aircraftTypeId?: string | null } = {};
      if (existing.familyId !== family.id) needsUpdate.familyId = family.id;
      if (existing.aircraftTypeId !== aircraftTypeId) needsUpdate.aircraftTypeId = aircraftTypeId;
      if (Object.keys(needsUpdate).length > 0) {
        await prisma.aircraftVariant.update({ where: { name: row.name }, data: needsUpdate });
        updated++;
      }
    } else {
      await prisma.aircraftVariant.create({ data: { name: row.name, familyId: family.id, aircraftTypeId } });
      created++;
    }
  }
  console.log(`  ✅ Variants: ${created} created, ${updated} updated, ${skipped} skipped`);
}

async function seedAirlines(rows: AirlineRow[]) {
  let created = 0, updated = 0;
  for (const row of rows) {
    if (!row.name) continue;
    const where = row.icaoCode
      ? { icaoCode: row.icaoCode }
      : row.iataCode ? { iataCode: row.iataCode } : { name: row.name };
    const existing = await prisma.airline.findFirst({ where: { OR: [where, { name: row.name }] } });
    if (existing) {
      const data: { name?: string; iataCode?: string | null; country?: string | null; callsign?: string | null } = {};
      if (!existing.name && row.name) data.name = row.name;
      if (!existing.iataCode && row.iataCode) data.iataCode = row.iataCode;
      if (!existing.country && row.country) data.country = row.country;
      if (!existing.callsign && row.callsign) data.callsign = row.callsign;
      if (Object.keys(data).length > 0) {
        await prisma.airline.update({ where: { id: existing.id }, data });
        updated++;
      }
    } else {
      await prisma.airline.create({
        data: {
          name: row.name,
          icaoCode: row.icaoCode || null,
          iataCode: row.iataCode || null,
          country: row.country || null,
          callsign: row.callsign || null,
        },
      });
      created++;
    }
  }
  console.log(`  ✅ Airlines: ${created} created, ${updated} updated`);
}

async function main() {
  console.log('🌱 Seeding aircraft hierarchy from CSV files…');

  // Check if data directory exists
  let files: string[] = [];
  try {
    files = readdirSync(DATA_DIR);
  } catch {
    console.log(`  📁 No data directory at ${DATA_DIR} — skipping hierarchy seed`);
    console.log('  💡 Run scripts/generate-aircraft-hierarchy-draft.ts to create draft CSVs');
    console.log('     then edit them before re-running this seed.');
    console.log('✅ Seed complete (no CSV files found)!');
    await prisma.$disconnect();
    return;
  }

  if (files.includes('manufacturers.csv')) {
    const rows = parseCSV(join(DATA_DIR, 'manufacturers.csv')) as ManufacturerRow[];
    console.log(`  📦 Loaded ${rows.length} manufacturer rows`);
    await seedManufacturers(rows);
  } else {
    console.log('  ℹ️  manufacturers.csv not found — skipping');
  }

  if (files.includes('families.csv')) {
    const rows = parseCSV(join(DATA_DIR, 'families.csv')) as FamilyRow[];
    console.log(`  📦 Loaded ${rows.length} family rows`);
    await seedFamilies(rows);
  } else {
    console.log('  ℹ️  families.csv not found — skipping');
  }

  if (files.includes('variants.csv')) {
    const rows = parseCSV(join(DATA_DIR, 'variants.csv')) as VariantRow[];
    console.log(`  📦 Loaded ${rows.length} variant rows`);
    await seedVariants(rows);
  } else {
    console.log('  ℹ️  variants.csv not found — skipping');
  }

  if (files.includes('airlines.csv')) {
    const rows = parseCSV(join(DATA_DIR, 'airlines.csv')) as AirlineRow[];
    console.log(`  📦 Loaded ${rows.length} airline rows`);
    await seedAirlines(rows);
  } else {
    console.log('  ℹ️  airlines.csv not found — skipping');
  }

  console.log('✅ Aircraft hierarchy seed complete!');
}

main()
  .catch((e) => {
    console.error('Seed failed:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
