/**
 * @module @spotterspace/shared
 * Shared types, constants, and validation logic used across the SpotterSpace monorepo.
 */

// ─── Enums ───────────────────────────────────────────────────────────────────

/** User roles for platform-level access control. */
export enum UserRole {
  USER = 'user',
  MODERATOR = 'moderator',
  ADMIN = 'admin',
}

/** Account status for users. */
export enum UserStatus {
  ACTIVE = 'active',
  SUSPENDED = 'suspended',
  BANNED = 'banned',
}

/** Experience level for spotter profiles. */
export enum ExperienceLevel {
  BEGINNER = 'beginner',
  INTERMEDIATE = 'intermediate',
  ADVANCED = 'advanced',
  PROFESSIONAL = 'professional',
}

/** Privacy mode for photo locations. */
export enum LocationPrivacyMode {
  EXACT = 'exact',
  APPROXIMATE = 'approximate',
  HIDDEN = 'hidden',
}

/** Photo moderation status from the upload pipeline. */
export enum ModerationStatus {
  PENDING = 'pending',
  APPROVED = 'approved',
  REJECTED = 'rejected',
  REVIEW = 'review',
}

/** Photo variant types generated by the image processing pipeline. */
export enum PhotoVariantType {
  THUMBNAIL = 'thumbnail',
  DISPLAY = 'display',
  FULL_RES = 'full_res',
  WATERMARKED = 'watermarked',
}

/** Notification types for the in-app notification system. */
export enum NotificationType {
  LIKE = 'like',
  COMMENT = 'comment',
  FOLLOW = 'follow',
  MENTION = 'mention',
  MODERATION = 'moderation',
  SYSTEM = 'system',
}

/** Reportable content types. */
export enum ReportTargetType {
  PHOTO = 'photo',
  COMMENT = 'comment',
  PROFILE = 'profile',
  ALBUM = 'album',
}

/** Reasons a user can report content. */
export enum ReportReason {
  INAPPROPRIATE = 'inappropriate',
  SPAM = 'spam',
  HARASSMENT = 'harassment',
  COPYRIGHT = 'copyright',
  OTHER = 'other',
}

/** Report resolution status. */
export enum ReportStatus {
  OPEN = 'open',
  REVIEWED = 'reviewed',
  RESOLVED = 'resolved',
  DISMISSED = 'dismissed',
}

// ─── Constants ───────────────────────────────────────────────────────────────

/** Individual user tier limits. */
export const USER_TIER_LIMITS = {
  free: {
    uploadsPerMonth: 50,
    minLongEdge: 800,
    maxResolution: 2048,
    maxFileSizeMB: 20,
    storageCapGB: 5,
  },
  premium: {
    uploadsPerMonth: 200,
    minLongEdge: 800,
    maxResolution: 4096,
    maxFileSizeMB: 50,
    storageCapGB: 25,
  },
} as const;

/** Community tier limits. */
export const COMMUNITY_TIER_LIMITS = {
  free: {
    maxMembers: 25,
    forumCategories: 1,
    sharedAlbums: 3,
    activeEvents: 2,
    adminSlots: 1,
  },
  standard: {
    maxMembers: 200,
    forumCategories: 5,
    sharedAlbums: 20,
    activeEvents: 10,
    adminSlots: 3,
  },
  large: {
    maxMembers: 1000,
    forumCategories: Infinity,
    sharedAlbums: Infinity,
    activeEvents: Infinity,
    adminSlots: 10,
  },
  enterprise: {
    maxMembers: Infinity,
    forumCategories: Infinity,
    sharedAlbums: Infinity,
    activeEvents: Infinity,
    adminSlots: 25,
  },
} as const;

/** Accepted image MIME types for upload. */
export const ACCEPTED_IMAGE_TYPES = [
  'image/jpeg',
  'image/png',
  'image/webp',
  'image/heic',
  'image/heif',
] as const;

/** Image derivative dimensions (long edge in pixels). */
export const IMAGE_VARIANT_SIZES = {
  thumbnail: 150,
  thumbnail16x9: 640,
  display: 640,
  fullRes2048: 2048,
  fullRes4096: 4096,
} as const;

// ─── Validation ──────────────────────────────────────────────────────────────

/** Username validation rules. */
export const USERNAME_RULES = {
  minLength: 3,
  maxLength: 30,
  pattern: /^[a-zA-Z0-9_-]+$/,
} as const;

/**
 * Validates a username against the platform rules.
 * @param username - The username to validate.
 * @returns An error message if invalid, or null if valid.
 */
export function validateUsername(username: string): string | null {
  if (username.length < USERNAME_RULES.minLength) {
    return `Username must be at least ${USERNAME_RULES.minLength} characters`;
  }
  if (username.length > USERNAME_RULES.maxLength) {
    return `Username must be at most ${USERNAME_RULES.maxLength} characters`;
  }
  if (!USERNAME_RULES.pattern.test(username)) {
    return 'Username can only contain letters, numbers, hyphens, and underscores';
  }
  return null;
}

/**
 * Result of validating an uploaded file.
 */
export interface UploadValidationResult {
  valid: boolean;
  error?: string;
}

/**
 * Validates an uploaded file against tier limits (file size and type only).
 * @param fileSizeBytes - The file size in bytes.
 * @param mimeType - The MIME type of the file.
 * @param tier - The user's subscription tier.
 * @returns An error message if invalid, or null if valid.
 */
export function validateUpload(
  fileSizeBytes: number,
  mimeType: string,
  tier: keyof typeof USER_TIER_LIMITS,
): string | null {
  if (!ACCEPTED_IMAGE_TYPES.includes(mimeType as (typeof ACCEPTED_IMAGE_TYPES)[number])) {
    return `Unsupported file type: ${mimeType}. Accepted: JPEG, PNG, WebP, HEIC`;
  }
  const limits = USER_TIER_LIMITS[tier];
  const maxBytes = limits.maxFileSizeMB * 1024 * 1024;
  if (fileSizeBytes > maxBytes) {
    return `File size exceeds ${limits.maxFileSizeMB} MB limit for ${tier} tier`;
  }
  return null;
}

/**
 * Validates image dimensions against tier limits.
 * @param width - Image width in pixels.
 * @param height - Image height in pixels.
 * @param tier - The user's subscription tier.
 * @returns UploadValidationResult with error message if invalid.
 */
export function validateImageDimensions(
  width: number,
  height: number,
  tier: keyof typeof USER_TIER_LIMITS,
): UploadValidationResult {
  const limits = USER_TIER_LIMITS[tier];
  const longEdge = Math.max(width, height);
  const shortEdge = Math.min(width, height);

  if (longEdge < limits.minLongEdge) {
    return {
      valid: false,
      error: `Image is too small. Minimum ${limits.minLongEdge}px on the long edge required (yours is ${longEdge}px).`,
    };
  }

  if (longEdge > limits.maxResolution) {
    return {
      valid: false,
      error: `Image resolution too high. Maximum ${limits.maxResolution}px on the long edge for ${tier} tier.`,
    };
  }

  return { valid: true };
}
